// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: .proto/pm0.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessService_Start_FullMethodName      = "/pm0.ProcessService/Start"
	ProcessService_List_FullMethodName       = "/pm0.ProcessService/List"
	ProcessService_Stop_FullMethodName       = "/pm0.ProcessService/Stop"
	ProcessService_StopAll_FullMethodName    = "/pm0.ProcessService/StopAll"
	ProcessService_Restart_FullMethodName    = "/pm0.ProcessService/Restart"
	ProcessService_RestartAll_FullMethodName = "/pm0.ProcessService/RestartAll"
	ProcessService_Logs_FullMethodName       = "/pm0.ProcessService/Logs"
	ProcessService_Delete_FullMethodName     = "/pm0.ProcessService/Delete"
	ProcessService_DeleteAll_FullMethodName  = "/pm0.ProcessService/DeleteAll"
	ProcessService_Show_FullMethodName       = "/pm0.ProcessService/Show"
	ProcessService_LogsClear_FullMethodName  = "/pm0.ProcessService/LogsClear"
	ProcessService_Rename_FullMethodName     = "/pm0.ProcessService/Rename"
)

// ProcessServiceClient is the client API for ProcessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessServiceClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error)
	StopAll(ctx context.Context, in *ExceptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error)
	Restart(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error)
	RestartAll(ctx context.Context, in *ExceptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error)
	Delete(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error)
	DeleteAll(ctx context.Context, in *ExceptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error)
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error)
	LogsClear(ctx context.Context, in *LogsClearRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type processServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessServiceClient(cc grpc.ClientConnInterface) ProcessServiceClient {
	return &processServiceClient{cc}
}

func (c *processServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, ProcessService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ProcessService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[0], ProcessService_Stop_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StopRequest, StopResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StopClient = grpc.ServerStreamingClient[StopResponse]

func (c *processServiceClient) StopAll(ctx context.Context, in *ExceptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[1], ProcessService_StopAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExceptRequest, StopResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StopAllClient = grpc.ServerStreamingClient[StopResponse]

func (c *processServiceClient) Restart(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[2], ProcessService_Restart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StopRequest, StopResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_RestartClient = grpc.ServerStreamingClient[StopResponse]

func (c *processServiceClient) RestartAll(ctx context.Context, in *ExceptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[3], ProcessService_RestartAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExceptRequest, StopResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_RestartAllClient = grpc.ServerStreamingClient[StopResponse]

func (c *processServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[4], ProcessService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_LogsClient = grpc.ServerStreamingClient[LogsResponse]

func (c *processServiceClient) Delete(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[5], ProcessService_Delete_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StopRequest, StopResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_DeleteClient = grpc.ServerStreamingClient[StopResponse]

func (c *processServiceClient) DeleteAll(ctx context.Context, in *ExceptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[6], ProcessService_DeleteAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExceptRequest, StopResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_DeleteAllClient = grpc.ServerStreamingClient[StopResponse]

func (c *processServiceClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowResponse)
	err := c.cc.Invoke(ctx, ProcessService_Show_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) LogsClear(ctx context.Context, in *LogsClearRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProcessService_LogsClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProcessService_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessServiceServer is the server API for ProcessService service.
// All implementations must embed UnimplementedProcessServiceServer
// for forward compatibility.
type ProcessServiceServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	List(context.Context, *emptypb.Empty) (*ListResponse, error)
	Stop(*StopRequest, grpc.ServerStreamingServer[StopResponse]) error
	StopAll(*ExceptRequest, grpc.ServerStreamingServer[StopResponse]) error
	Restart(*StopRequest, grpc.ServerStreamingServer[StopResponse]) error
	RestartAll(*ExceptRequest, grpc.ServerStreamingServer[StopResponse]) error
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error
	Delete(*StopRequest, grpc.ServerStreamingServer[StopResponse]) error
	DeleteAll(*ExceptRequest, grpc.ServerStreamingServer[StopResponse]) error
	Show(context.Context, *ShowRequest) (*ShowResponse, error)
	LogsClear(context.Context, *LogsClearRequest) (*emptypb.Empty, error)
	Rename(context.Context, *RenameRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProcessServiceServer()
}

// UnimplementedProcessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessServiceServer struct{}

func (UnimplementedProcessServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedProcessServiceServer) List(context.Context, *emptypb.Empty) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProcessServiceServer) Stop(*StopRequest, grpc.ServerStreamingServer[StopResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedProcessServiceServer) StopAll(*ExceptRequest, grpc.ServerStreamingServer[StopResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StopAll not implemented")
}
func (UnimplementedProcessServiceServer) Restart(*StopRequest, grpc.ServerStreamingServer[StopResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedProcessServiceServer) RestartAll(*ExceptRequest, grpc.ServerStreamingServer[StopResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RestartAll not implemented")
}
func (UnimplementedProcessServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedProcessServiceServer) Delete(*StopRequest, grpc.ServerStreamingServer[StopResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProcessServiceServer) DeleteAll(*ExceptRequest, grpc.ServerStreamingServer[StopResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DeleteAll not implemented")
}
func (UnimplementedProcessServiceServer) Show(context.Context, *ShowRequest) (*ShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedProcessServiceServer) LogsClear(context.Context, *LogsClearRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogsClear not implemented")
}
func (UnimplementedProcessServiceServer) Rename(context.Context, *RenameRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedProcessServiceServer) mustEmbedUnimplementedProcessServiceServer() {}
func (UnimplementedProcessServiceServer) testEmbeddedByValue()                        {}

// UnsafeProcessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessServiceServer will
// result in compilation errors.
type UnsafeProcessServiceServer interface {
	mustEmbedUnimplementedProcessServiceServer()
}

func RegisterProcessServiceServer(s grpc.ServiceRegistrar, srv ProcessServiceServer) {
	// If the following call pancis, it indicates UnimplementedProcessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessService_ServiceDesc, srv)
}

func _ProcessService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_Stop_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).Stop(m, &grpc.GenericServerStream[StopRequest, StopResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StopServer = grpc.ServerStreamingServer[StopResponse]

func _ProcessService_StopAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExceptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).StopAll(m, &grpc.GenericServerStream[ExceptRequest, StopResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StopAllServer = grpc.ServerStreamingServer[StopResponse]

func _ProcessService_Restart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).Restart(m, &grpc.GenericServerStream[StopRequest, StopResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_RestartServer = grpc.ServerStreamingServer[StopResponse]

func _ProcessService_RestartAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExceptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).RestartAll(m, &grpc.GenericServerStream[ExceptRequest, StopResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_RestartAllServer = grpc.ServerStreamingServer[StopResponse]

func _ProcessService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_LogsServer = grpc.ServerStreamingServer[LogsResponse]

func _ProcessService_Delete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).Delete(m, &grpc.GenericServerStream[StopRequest, StopResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_DeleteServer = grpc.ServerStreamingServer[StopResponse]

func _ProcessService_DeleteAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExceptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).DeleteAll(m, &grpc.GenericServerStream[ExceptRequest, StopResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_DeleteAllServer = grpc.ServerStreamingServer[StopResponse]

func _ProcessService_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_LogsClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).LogsClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_LogsClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).LogsClear(ctx, req.(*LogsClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessService_ServiceDesc is the grpc.ServiceDesc for ProcessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pm0.ProcessService",
	HandlerType: (*ProcessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _ProcessService_Start_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProcessService_List_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _ProcessService_Show_Handler,
		},
		{
			MethodName: "LogsClear",
			Handler:    _ProcessService_LogsClear_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _ProcessService_Rename_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stop",
			Handler:       _ProcessService_Stop_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StopAll",
			Handler:       _ProcessService_StopAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Restart",
			Handler:       _ProcessService_Restart_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestartAll",
			Handler:       _ProcessService_RestartAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _ProcessService_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Delete",
			Handler:       _ProcessService_Delete_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteAll",
			Handler:       _ProcessService_DeleteAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: ".proto/pm0.proto",
}
